version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: scope

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: zod
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: "chore"
      include: scope
